United command "install" and "installfile".

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -199,7 +199,6 @@ USAGE="
 
      Software Management:
         install, in             Install applications.
-        installfile             Install applications from archive.
         remove, rm              Remove applications.
         list                    List installed applications.
         search, se              Search image version on private registry.
@@ -218,15 +217,9 @@ USAGE="
 
 USAGE_INSTALL="
 install (in) <app>:<version>
+install (in) <filename>
 
-Install smilart applications with specified capabilities.
-
-";
-
-USAGE_INSTALLFILE="
-installfile <path>
-
-Install smilart applications with specified capabilities from gzip and tar archive.
+Install smilart applications with specified capabilities from repository and from gzip or tar archive.
 
 ";
 
@@ -322,7 +315,6 @@ List all defined repositories.
 
 ## Function for case
 install_func(){
-
     local SAM_INSTALL_DOCKER_ID;
     local SAM_INSTALL_REPO_ID;
     local SAM_INSTALL_VERSION;
@@ -334,122 +326,110 @@ install_func(){
     local SAM_INSTALL_EMAIL;
     local SAM_INSTALL_COMMAND_OPTIONS;
     local SAM_PREFIX_IMAGE_DOCKER;
+    
+    local CHECK_APP_IN_FILE
 
-    SAM_INSTALL_VERSION=`echo "$1" | awk -F '/' '{print $NF}' | awk -F ':' '{print $2}'`;
-    if [[ -z $SAM_INSTALL_VERSION ]];then
-        echo -e "\E[31mERROR: Version in string '$1' is not found.">&2;tput sgr0;
-        exit 1;
-    fi;
-    SAM_INSTALL_APP=`echo "$1" | awk -F '/' '{print $NF}' | awk -F ':' '{print $1}'`;
-    SAM_INSTALL_REPOS_NAME=`echo "$1" | sed "s#\$SAM_INSTALL_APP\:\$SAM_INSTALL_VERSION##g" | sed 's/\/$//'`;
-    if [[ -z $SAM_INSTALL_REPOS_NAME ]];then
-        SAM_INSTALL_REPOS_NAME=`sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS where ReposFlag='*'" | sed 's/\/$//' | awk -F '/' '{print $NF}'`;
-    fi;
-    #Exist repository in db?
-    if [[ -z `sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"` ]];then
-        echo -e "\E[31mERROR: Not found name repository '$SAM_INSTALL_REPOS_NAME' in db.">&2;tput sgr0;
-        exit 1;
-    fi;
-    #Exist app in db?
-    if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ImageName from $SAM_DB_TABLE_INSTALL_APPS where ImageName='$SAM_INSTALL_APP'"` ]];then
-        echo -e "\E[31mERROR: App '$SAM_INSTALL_APP' found in db.">&2;tput sgr0;
-        exit 1;
-    fi;
-    #logging
-    SAM_INSTALL_USER=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUser from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'" | sed 's/[\ \t]//g'`;
-    SAM_PREFIX_IMAGE_DOCKER=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUrl from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'" | sed 's/\/$//' | awk -F '/' '{print $NF}'`;
-    if [[ -n $SAM_INSTALL_USER ]];then
-        SAM_INSTALL_PASSWORD=`sqlite3 $SAM_DB_SQLITE "SELECT ReposPass from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
-        SAM_INSTALL_EMAIL=`sqlite3 $SAM_DB_SQLITE "SELECT ReposEmail from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
-        SAM_INSTALL_REPOS_URL=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUrl from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
-        if [ -n "$SAM_INSTALL_EMAIL" ];then
-            SAM_INSTALL_COMMAND_OPTIONS="--email=$SAM_INSTALL_EMAIL";
-        else
-            SAM_INSTALL_COMMAND_OPTIONS='--email=none';
-        fi;
-        docker login --username=$SAM_INSTALL_USER --password=`echo "$SAM_INSTALL_PASSWORD" | base64 -d` $SAM_INSTALL_COMMAND_OPTIONS $SAM_PREFIX_IMAGE_DOCKER 2>&1 > /dev/null;
-        if [[ $? -ne 0 ]]; then
-            echo -e "\E[31mERROR: Wrong login/password or url from repository.">&2;tput sgr0;
+    if [ -f "$1" ];then
+	# Find file "repositories"
+	CHECK_APP_IN_FILE="`tar -xOf $1 repositories 2>&1`";
+    	if [[ $? -ne 0 ]]; then
+            echo -e "\E[31mERROR: File repositories not found in archive.">&2;tput sgr0;
+            exit 1;
+    	fi;
+	if [[ -z "$CHECK_APP_IN_FILE" ]]; then
+            echo -e "\E[31mERROR: Incorrectly created archive. File repositories is bad.">&2;tput sgr0;
             exit 1;
         fi;
+	SAM_PREFIX_IMAGE_DOCKER=`echo "$CHECK_APP_IN_FILE" | awk -F '"' ' {print $2} ' | sed "s/ /:/g" | awk -F '/' '{print $1}'`;
+        SAM_INSTALL_APP=`echo "$CHECK_APP_IN_FILE" | awk -F '"' ' {print $2} ' | sed "s/ /:/g" | awk -F '/' '{print $NF}'`;
+        SAM_INSTALL_VERSION=`echo "$CHECK_APP_IN_FILE" | awk -F '"' ' {print $4} ' | sed "s/ /:/g"`;
+        if [[ -z $SAM_PREFIX_IMAGE_DOCKER ]] || [[ -z $SAM_INSTALL_VERSION ]]; then
+            echo -e "\E[31mERROR: Incorrect file 'repositories' in archive.">&2;tput sgr0;
+            echo "Not found application name or version in file.";
+            echo "May be incorrectly created archive.";
+            exit 1;
+        fi;
+      
+	if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ImageName from $SAM_DB_TABLE_INSTALL_APPS where ImageName='$SAM_INSTALL_APP'"` ]];then
+            echo -e "\E[31mERROR: Application name '$SAM_INSTALL_APP' exist in db.">&2;tput sgr0;
+            exit 1;
+
+        fi;
+        echo "Loading image '$SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION'.";
+        docker load -i $1;
+        if [[ $? -ne 0 ]]; then
+            echo -e "\E[31mERROR: Loading image.">&2;tput sgr0;
+            exit 1;
+        fi;
+	
+	SAM_INSTALL_DOCKER_ID=`docker images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION:" | awk -F ':' '{print $NF}'`;
+        SAM_INSTALL_REPO_ID=0;
+    else
+
+        # if $1 in docker repo
+        SAM_INSTALL_VERSION=`echo "$1" | awk -F '/' '{print $NF}' | awk -F ':' '{print $2}'`;
+        if [[ -z $SAM_INSTALL_VERSION ]];then
+            echo -e "\E[31mERROR: Version in string '$1' is not found.">&2;tput sgr0;
+            exit 1;
+        fi;
+        SAM_INSTALL_APP=`echo "$1" | awk -F '/' '{print $NF}' | awk -F ':' '{print $1}'`;
+        SAM_INSTALL_REPOS_NAME=`echo "$1" | sed "s#\$SAM_INSTALL_APP\:\$SAM_INSTALL_VERSION##g" | sed 's/\/$//'`;
+        if [[ -z $SAM_INSTALL_REPOS_NAME ]];then
+            SAM_INSTALL_REPOS_NAME=`sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS where ReposFlag='*'" | sed 's/\/$//' | awk -F '/' '{print $NF}'`;
+        fi;
+        #Exist repository in db?
+        if [[ -z `sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"` ]];then
+            echo -e "\E[31mERROR: Not found name repository '$SAM_INSTALL_REPOS_NAME' in db.">&2;tput sgr0;
+            exit 1;
+        fi;
+        #Exist app in db?
+        if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ImageName from $SAM_DB_TABLE_INSTALL_APPS where ImageName='$SAM_INSTALL_APP'"` ]];then
+            echo -e "\E[31mERROR: App '$SAM_INSTALL_APP' found in db.">&2;tput sgr0;
+            exit 1;
+        fi;
+        #logging
+        SAM_INSTALL_USER=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUser from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'" | sed 's/[\ \t]//g'`;
+        SAM_PREFIX_IMAGE_DOCKER=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUrl from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'" | sed 's/\/$//' | awk -F '/' '{print $NF}'`;
+        if [[ -n $SAM_INSTALL_USER ]];then
+            SAM_INSTALL_PASSWORD=`sqlite3 $SAM_DB_SQLITE "SELECT ReposPass from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
+            SAM_INSTALL_EMAIL=`sqlite3 $SAM_DB_SQLITE "SELECT ReposEmail from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
+            SAM_INSTALL_REPOS_URL=`sqlite3 $SAM_DB_SQLITE "SELECT ReposUrl from $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
+            if [ -n "$SAM_INSTALL_EMAIL" ];then
+                SAM_INSTALL_COMMAND_OPTIONS="--email=$SAM_INSTALL_EMAIL";
+            else
+                SAM_INSTALL_COMMAND_OPTIONS='--email=none';
+            fi;
+            docker login --username=$SAM_INSTALL_USER --password=`echo "$SAM_INSTALL_PASSWORD" | base64 -d` $SAM_INSTALL_COMMAND_OPTIONS $SAM_PREFIX_IMAGE_DOCKER 2>&1 > /dev/null;
+            if [[ $? -ne 0 ]]; then
+                echo -e "\E[31mERROR: Wrong login/password or url from repository.">&2;tput sgr0;
+            fi;
+        fi;
+        SAM_INSTALL_REPO_ID=`sqlite3 $SAM_DB_SQLITE "SELECT Id FROM $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
+        docker pull $SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION;
+        if [[ $? -ne 0 ]]; then
+            echo -e "\E[31mERROR: Not download smilart applications.">&2;tput sgr0;
+            echo "Find local application.";
+            SAM_INSTALL_REPO_ID='';
+        fi;
+        SAM_INSTALL_DOCKER_ID=`docker images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION:" | awk -F ':' '{print $NF}'`;
+        if [[ -z $SAM_INSTALL_DOCKER_ID ]];then
+            echo -e "\E[31mERROR: Not found smilart applications '$SAM_INSTALL_APP:$SAM_INSTALL_VERSION'.">&2;tput sgr0;
+            exit 1;
+        fi;
+	docker logout 2>&1 > /dev/null;
     fi;
-    SAM_INSTALL_REPO_ID=`sqlite3 $SAM_DB_SQLITE "SELECT Id FROM $SAM_DB_TABLE_REPOS where ReposName='$SAM_INSTALL_REPOS_NAME'"`;
-    docker pull $SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION;
-    if [[ $? -ne 0 ]]; then
-        echo -e "\E[31mERROR: Not download smilart applications.">&2;tput sgr0;
-        echo "Find local application.";
-        SAM_INSTALL_REPO_ID='';
-    fi;
-    SAM_INSTALL_DOCKER_ID=`docker images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION:" | awk -F ':' '{print $NF}'`;
-    if [[ -z $SAM_INSTALL_DOCKER_ID ]];then
-        echo -e "\E[31mERROR: Not found smilart applications '$SAM_INSTALL_APP:$SAM_INSTALL_VERSION'.">&2;tput sgr0;
-        exit 1;
-    fi;
+
+    #
     create_tag_app $SAM_INSTALL_DOCKER_ID $SAM_INSTALL_APP:$SAM_INSTALL_VERSION;
     echo;
     echo -e "\E[32mInstalling app $SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION.";tput sgr0;
     install_app_func $SAM_INSTALL_DOCKER_ID;    
-
-    docker logout 2>&1 > /dev/null;
-    
     save_app_in_db $SAM_INSTALL_DOCKER_ID $SAM_INSTALL_APP $SAM_INSTALL_VERSION $SAM_INSTALL_REPO_ID;
     if [[ $? -ne 0 ]]; then
         echo -e "\E[31mERROR: Not save in db. '$SAM_INSTALL_DOCKER_ID $SAM_INSTALL_APP $SAM_INSTALL_VERSION $SAM_INSTALL_REPO_ID'">&2;tput sgr0;
         exit 1;
     fi;
     echo -e "\E[32mApp $SAM_PREFIX_IMAGE_DOCKER/$SAM_INSTALL_APP:$SAM_INSTALL_VERSION installed.";tput sgr0;
-    echo;
-}
-
-installfile_func(){
-    local SAM_INSTALLFILE_NAME;
-    local SAM_INSTALLFILE_APP;
-    local SAM_INSTALLFILE_VERSION;
-    local SAM_INSTALLFILE_REPO_ID;
-    local SAM_INSTALLFILE_DOCKER_ID;
-
-    # Find file "repositories"
-    tar -xf $1 repositories;
-    if [[ $? -ne 0 ]]; then
-        echo -e "\E[31mERROR: File repositories not found in archive.">&2;tput sgr0;
-        echo "May be incorrectly created archive.";
-        exit 1;
-    fi;
-    # SAM_INSTALLFILE_NAME = PREFIX_IMAGE_DOCKER/$SAM_INSTALLFILE_APP
-    SAM_INSTALLFILE_NAME=`cat repositories | awk -F '"' ' {print $2} ' | sed "s/ /:/g"`;
-    SAM_INSTALLFILE_APP=`cat repositories | awk -F '"' ' {print $2} ' | sed "s/ /:/g" | awk -F '/' '{print $NF}'`;
-    SAM_INSTALLFILE_VERSION=`cat repositories | awk -F '"' ' {print $4} ' | sed "s/ /:/g"`;
-    if [[ -z $SAM_INSTALLFILE_NAME ]] || [[ -z $SAM_INSTALLFILE_VERSION ]]; then
-        echo -e "\E[31mERROR: Incorrect file 'repositories' in archive.">&2;tput sgr0;
-        echo "Not found application name or version in file.";
-        echo "May be incorrectly created archive.";
-        exit 1;
-    fi;
-    rm -f repositories;
-    if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ImageName from $SAM_DB_TABLE_INSTALL_APPS where ImageName='$SAM_INSTALLFILE_APP'"` ]];then
-         echo -e "\E[31mERROR: Application name '$SAM_INSTALLFILE_APP' exist in db.">&2;tput sgr0;
-         exit 1;
-
-    fi;
-    echo "Loading image '$SAM_INSTALLFILE_NAME:$SAM_INSTALLFILE_VERSION'.";
-    docker load -i $1;
-    if [[ $? -ne 0 ]]; then
-        echo -e "\E[31mERROR: Loading image.">&2;tput sgr0;
-        exit 1;
-    fi;
-    SAM_INSTALLFILE_DOCKER_ID=`docker images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$SAM_INSTALLFILE_NAME:$SAM_INSTALLFILE_VERSION:" | awk -F ':' '{print $NF}'`;
-    SAM_INSTALLFILE_REPO_ID=0;
-    # Install app
-    create_tag_app $SAM_INSTALLFILE_DOCKER_ID $SAM_INSTALLFILE_APP:$SAM_INSTALLFILE_VERSION;
-    echo;
-    echo -e "\E[32mInstalling app $SAM_INSTALLFILE_NAME:$SAM_INSTALLFILE_VERSION.";tput sgr0;
-    install_app_func $SAM_INSTALLFILE_DOCKER_ID;
-    save_app_in_db $SAM_INSTALLFILE_DOCKER_ID $SAM_INSTALLFILE_APP $SAM_INSTALLFILE_VERSION $SAM_INSTALLFILE_REPO_ID;
-    if [[ $? -ne 0 ]]; then
-        echo -e "\E[31mERROR: Not saving in db. '$SAM_INSTALLFILE_DOCKER_ID $SAM_INSTALLFILE_APP $SAM_INSTALLFILE_VERSION $SAM_INSTALLFILE_REPO_ID'">&2;tput sgr0;
-        exit 1;
-    fi;
-    echo -e "\E[32mApp $SAM_INSTALLFILE_NAME:$SAM_INSTALLFILE_VERSION installed.";tput sgr0;
     echo;
 }
 
@@ -739,10 +719,6 @@ help_func(){
             echo "$USAGE_UPGRADE";
             exit 0
             ;;
-        installfile)
-            echo "$USAGE_INSTALLFILE";
-            exit 0
-            ;;
         remove|rm)
             echo "$USAGE_REMOVE";
             exit 0
@@ -888,11 +864,6 @@ while true ; do
                 remove|rm)
                     shift;
                     remove_func $1;
-                    exit 0
-                    ;;
-                installfile)
-                    shift;
-                    installfile_func $1;
                     exit 0
                     ;;
                 upgrade|up)
