Initial

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -184,7 +184,7 @@ list_apps_in_db_func () {
 }
 
 list_repos_in_db_func () {
-	sqlite3 $SAM_DB_SQLITE "SELECT * from $SAM_DB_TABLE_REPOS" | awk -F '|' '{print $1, $2, $3, $4, $5, $6}';
+	sqlite3 $SAM_DB_SQLITE "SELECT id, ReposFlag, ReposName, ReposUrl, ReposUser, ReposPass, ReposEmail from $SAM_DB_TABLE_REPOS" | awk -F '|' '{print $1, $2, $3, $4, $5, $6}';
 }
 #Exist repos name?
 exist_repos_name_in_db_func() {
@@ -200,299 +200,357 @@ exist_repos_name_in_db_func() {
                             fi; \
                         done;` ]];then
 		echo -e "\E[31mERROR: Repository name '$SAM_DB_TABLE_REPOS_NAME' is not found in db.">&2;tput sgr0;
-		echo "Existing repositories look with 'sam --repos-list'.";
+		echo "Existing repositories look with 'sam help listrepos'.";
 		exit 1;
 	fi;
 }
 
+###Help section
 USAGE="
-Options:
-	-f  [archive.tar]	Load image from tar archive
-	-i  [image]:[version]	Install selected application
-	-u  [image]:[version]	Uninstall selected application
-	-x  [-f:-i:-u] 		Debug mode
-	-I  [image]:[version]	Print application info
-	-c  [image]:[version]	Copy metadata from image to directory /tmp
-	-l  			List installed applications
-	-h  			Help
+  Usage:
+        sam [--global-options] <command> [--command-options] [arguments]
 
-Environments:
-	SAM_DB_LIST		SAM database, default: SAM_DB_LIST=$SAM_DB_LIST
+  Global Options:
+        --help, -h              Help.
+        --debug, -x             Debug mode.
+
+
+  Commands:
+        help, ?                 Print help.
+     
+     Software Management:
+        install, in             Install applications.
+        installfile             Install applications from archive.
+        remove, rm              Remove applications.
+        list                    List installed applications.
+        info                    Print application info.
+
+     Repository Management:
+        addrepo, ar             Add a new repository.
+        removerepo, rr          Remove specified repository.
+        modifyrepo, mr          Modify specified repository.
+        listrepos, lr           List all defined repositories.
+
+
+  Environments:
 	BIN_DIR			Path to directory with executable files, default: BIN_DIR=$BIN_DIR
 ";
 
-while getopts "li:f:u:c:xI:h-:" OPTION
+USAGE_INSTALL='
+install (in) [repo/]<app>:<version>
+
+Install smilart applications with specified capabilities.
+
+';
+USAGE_INSTALLFILE="
+install <path>
+
+Install smilart applications with specified capabilities from gzip and tar archive.
+
+";
+
+USAGE_REMOVE="
+remove (rm) <name>
+
+Remove smilart applications with specified capabilities.
+
+";
+
+USAGE_LIST="
+list [options]
+
+List all install smilart applications.
+
+  Command options:
+    --raw                       List all install smilart applications in RAW format.
+
+";
+
+USAGE_INFO="
+info <name>
+
+Print application info.
+
+";
+
+USAGE_ADDREPO="
+addrepo (ar) [options] <name> <url> [<username> <password> <mail>]
+
+Add a repository to the system.
+
+  Command options:
+    --default                   Add the repository as default.
+
+";
+
+USAGE_REMOVEREPO="
+removerepo (rr) <id|name>
+
+Remove repository specified by name or number.
+
+";
+
+USAGE_MODIFYREPO="
+modifyrepo (mr) <id> [--default] [--name <name>] [--url <url>] [--username <username>] [--password <password>] [--email <email>]
+
+Modify properties of repositories specified.
+
+  Command options:
+-d  --default                   Set priority of the repository.
+    --name                      Set a descriptive name for the repository.
+    --url                       Set a url for the repository.
+    --username                  Set the user name for authentication to the server.
+    --password                  Set the password for authentication to the server.
+    --email                     Set the email for authentication to the server. 
+
+";
+
+USAGE_LISTREPOS="
+repos (lr) [options]
+
+List all defined repositories.
+    --raw                       List all defined repositories in RAW format.
+";
+
+###Function for case
+install_func(){
+echo "OK"
+}
+
+installfile_func(){
+echo "OK"
+}
+
+remove_func(){
+echo "OK"
+}
+
+list_func(){
+echo "OK"
+}
+
+info_func(){
+echo "OK"
+}
+
+addrepo_func(){
+    #Default repo?
+    SAM_DB_TABLE_REPOS_FLAG='';
+    if [[ -n `echo $SAM_ARGUMENTS | grep -w '\-\-default'` ]];then
+         SAM_ARGUMENTS=`echo "$SAM_ARGUMENTS" | sed 's/--default //'`;
+         SAM_DB_TABLE_REPOS_FLAG='*';
+    fi;
+    IFS=' ' read -a ARR_OF_ARG <<< "$SAM_ARGUMENTS";
+    if [[ -z ${ARR_OF_ARG[0]} ]] || [[ -z ${ARR_OF_ARG[1]} ]];then
+         echo "$USAGE_ADDREPO";
+         echo -e "\E[31mERROR: Argument for "sam addrepo" is not correct.">&2;tput sgr0;
+         exit 1;
+    fi;
+    SAM_DB_TABLE_REPOS_NAME="${ARR_OF_ARG[0]}";
+    SAM_DB_TABLE_REPOS_URL="${ARR_OF_ARG[1]}";
+    SAM_DB_TABLE_REPOS_USER="${ARR_OF_ARG[2]}";
+    SAM_DB_TABLE_REPOS_PASS="${ARR_OF_ARG[3]}";
+    SAM_DB_TABLE_REPOS_EMAIL="${ARR_OF_ARG[4]}";
+    if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS" | \
+         while read line; do \
+             if [ $line == $SAM_DB_TABLE_REPOS_NAME ];then \
+                  echo $line; \
+                  break; \
+             fi; \
+         done;` ]];then
+         echo -e "\E[31mERROR: Repository name '$SAM_DB_TABLE_REPOS_NAME' exist in db.">&2;tput sgr0;
+         exit 1;
+        fi;
+    SAM_DB_TABLE_REPOS_PASS=`echo "$SAM_DB_TABLE_REPOS_PASS" | base64`;
+    
+    #save in db
+    sqlite3 $SAM_DB_SQLITE "insert into $SAM_DB_TABLE_REPOS (ReposFlag,ReposName,ReposUrl,ReposUser,ReposPass,ReposEmail) values ('$SAM_DB_TABLE_REPOS_FLAG','$SAM_DB_TABLE_REPOS_NAME','$SAM_DB_TABLE_REPOS_URL','$SAM_DB_TABLE_REPOS_USER','$SAM_DB_TABLE_REPOS_PASS','$SAM_DB_TABLE_REPOS_EMAIL');";
+    if [[ -n $SAM_DB_TABLE_REPOS_FLAG ]];then
+	sqlite3 $SAM_DB_SQLITE "update $SAM_DB_TABLE_REPOS SET ReposFlag=' '";
+	sqlite3 $SAM_DB_SQLITE "update $SAM_DB_TABLE_REPOS SET ReposFlag='*' where ReposName='$SAM_DB_TABLE_REPOS_NAME'";
+    fi;
+    unset SAM_DB_TABLE_REPOS_FLAG;
+    unset SAM_DB_TABLE_REPOS_URL;
+    unset SAM_DB_TABLE_REPOS_NAME;
+    unset SAM_DB_TABLE_REPOS_USER;
+    unset SAM_DB_TABLE_REPOS_PASS;
+    unset SAM_DB_TABLE_REPOS_EMAIL;
+}
+
+removerepo_func(){
+    #Found repo name in db?
+    if [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT ReposName from $SAM_DB_TABLE_REPOS" | \
+        while read line; do \
+            if [ $line == $SAM_ARGUMENTS ];then \
+                 echo $line; \
+                 break; \
+            fi; \
+        done;` ]];then
+
+	#delete in db
+	#Default repository?
+	if [[ '*' == `sqlite3 $SAM_DB_SQLITE "select ReposFlag from $SAM_DB_TABLE_REPOS where ReposName='$SAM_ARGUMENTS'"` ]]; then
+		echo -e "\E[31mERROR: Repository with name '$SAM_ARGUMENTS' is default.">&2;tput sgr0;
+        	exit 1;
+	fi;
+	sqlite3 $SAM_DB_SQLITE "delete from $SAM_DB_TABLE_REPOS where ReposName='$SAM_ARGUMENTS'";
+
+    #Found id in db?	
+    elif [[ -n `sqlite3 $SAM_DB_SQLITE "SELECT Id from $SAM_DB_TABLE_REPOS" | \
+        while read line; do \
+            if [ $line == $SAM_ARGUMENTS ];then \
+                 echo $line; \
+                 break; \
+	    fi; \
+	done;` ]];then
+	
+	#delete in db
+        #Default repository?
+        if [[ '*' == `sqlite3 $SAM_DB_SQLITE "select ReposFlag from $SAM_DB_TABLE_REPOS where id='$SAM_ARGUMENTS'"` ]]; then
+                echo -e "\E[31mERROR: Repository with number '$SAM_ARGUMENTS' is default.">&2;tput sgr0;
+                exit 1; 
+        fi;
+        sqlite3 $SAM_DB_SQLITE "delete from $SAM_DB_TABLE_REPOS where Id='$SAM_ARGUMENTS'";
+    else
+	    echo -e "\E[31mERROR: Repository name and number '$SAM_ARGUMENTS' not found in db.">&2;tput sgr0;
+            exit 1;
+
+    fi;
+}
+
+modifyrepo_func(){
+    SAM_DB_TABLE_REPOS_ID=`echo $SAM_ARGUMENTS |  awk ' {print $1} '`
+    if [[ -z `sqlite3 $SAM_DB_SQLITE "SELECT Id from $SAM_DB_TABLE_REPOS" | \
+        while read line; do \
+            if [ $line == $SAM_DB_TABLE_REPOS_ID ];then \
+                 echo $line; \
+                 break; \
+            fi; \
+        done;` ]];then
+	echo -e "\E[31mERROR: Repository number '$SAM_DB_TABLE_REPOS_ID' not found in db.">&2;tput sgr0;
+	exit 1;
+    fi;
+    
+	
+}
+
+listrepos_func(){
+    echo;
+    echo "      List repositories:";
+    echo;
+    LIST_REPOSITORIES=`sqlite3 -header $SAM_DB_SQLITE "SELECT id as Num, ReposFlag as Def, ReposName as Name, ReposUrl as Url, ReposUser as User FROM $SAM_DB_TABLE_REPOS" |  column -t -s '|' -o ' | '`;
+
+    LIST_REPOSITORIES_MAX_LINE=`echo "$LIST_REPOSITORIES" | wc -L`;
+    echo "$LIST_REPOSITORIES" | sed -e "1 a `for i in \`seq 1 $LIST_REPOSITORIES_MAX_LINE\`; do echo -n '-';  done`"
+    echo;
+    unset LIST_REPOSITORIES_MAX_LINE;
+    unset LIST_REPOSITORIES;
+}
+
+###Case section
+SAM_ARGUMENTS=''
+#set -vx
+while getopts ":h-:" OPTIONS
 do
-    case $OPTION in
+    case $OPTIONS in
+        -) case "${OPTARG}" in
+                help)
+                    echo "$USAGE";
+                    exit 0
+                    ;;
 
-	l ) echo;
-	    echo "      List apps:";
-	    echo;
-	    # Print repository
-	    list_apps_in_db_func | awk '{print $3, $4, $5}' | \
-		while read line; do \
-		    SAM_DB_IMAGE_NAME=`echo $line | awk '{print $1}'`;
-		    SAM_DB_IMAGE_VERSION=`echo $line | awk '{print $2}'`;
-		    SAM_DB_IMAGE_REPOS=`echo $line | awk '{print $3}'`;
-		    PRINT_IMAGE_REPOS='';
-		    # Number?
-		    if [[ `expr "$SAM_DB_IMAGE_REPOS" : '-\?[0-9]\+$'` == '0' ]]; then
-			PRINT_IMAGE_REPOS='unknown';
-		    else
-			#Exist number?
-		       case "$SAM_DB_IMAGE_REPOS" in
-			"0")	PRINT_IMAGE_REPOS='archive'
-			    ;;
-			*)	if [[ `sqlite3 $SAM_DB_SQLITE "SELECT id from $SAM_DB_TABLE_REPOS" | grep -w $SAM_DB_IMAGE_REPOS` != $SAM_DB_IMAGE_REPOS ]]; then
-				    PRINT_IMAGE_REPOS='unknown';
-				else
-				    PRINT_IMAGE_REPOS=`sqlite3 $SAM_DB_SQLITE "SELECT ReposName FROM $SAM_DB_TABLE_REPOS WHERE id='$SAM_DB_IMAGE_REPOS'"`;
-				fi
-			    ;;
-		       esac;
-		    fi;
-		    echo "$SAM_DB_IMAGE_NAME:$SAM_DB_IMAGE_VERSION $PRINT_IMAGE_REPOS" | column -t;
-		done
-	    echo;
-	    exit 0
-	  ;;
-
-	x ) set -vx
-	  ;;
-
-	f ) if [ -f $OPTARG ]; then
-
-		## Find image name to archive
-		# Find file "repositories"
-		tar -xf $OPTARG repositories;
-		if [[ $? -ne 0 ]]; then
-		    echo -e "\E[31mERROR: File repositories not found in archive.">&2;tput sgr0;
-		    echo "May be incorrectly created archive.";
-		    exit 1;
-		fi;
-		# Correct file "repositories"
-		IMAGE=`cat repositories | awk -F '"' ' {print $2,$4} ' | sed "s/ /:/g"`;
-		if [[ -z $IMAGE ]]; then
-		    echo -e "\E[31mERROR: Incorrect file 'repositories' in archive.">&2;tput sgr0;
-		    echo "Not found image name in file.";
-		    echo "May be incorrectly created archive.";
-		    exit 1;
-		fi;
-		rm -f repositories;
-		##
-		if [[ -z `list_apps_in_db_func | awk 'BEGIN {OFS = ":"} {print $3, $4}' | grep "$IMAGE"` ]];then
-			echo "App not found in db.";
-			# Load image
-			echo "Loading image $IMAGE.";
-			docker load -i $OPTARG;
-			if [[ $? -ne 0 ]]; then
-			    echo -e "\E[31mERROR: Loading image.">&2;tput sgr0;
-			    exit 1;
-			fi;
-			# Install app
-			save_apps_to_db_sqlite_func;
-			install_apps_func;
-			echo -e "\E[32mApp $IMAGE installed.";tput sgr0;
-			echo;
-		else 
-			echo -e "\E[31mERROR: App exist in db.">&2;tput sgr0;
-			exit 1;
-		fi;
-	   else
-		echo -e "\E[31m$0: Archive image is not defined." >&2;tput sgr0;
-		exit 1;
-	   fi
-	  ;;
-
-	i ) IMAGE=$OPTARG;
-	   image_latest_func;
-	   # Installed app?
-	   if [[ -n `list_apps_in_db_func | awk 'BEGIN {OFS = ":"} {print $3, $4}' | grep "$IMAGE"` ]];then
-		echo -e "\E[31mERROR: App found in db. Stop installation.">&2;tput sgr0;
-		exit 1;
-	   fi;
-	   # Exist image?
-	   if [[ -z `docker images --no-trunc | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2} ' | sed "s/ /:/g" | grep "$IMAGE"` ]];then
-		echo -e "\E[31mERROR: Image not found in registry docker. Stop installation.">&2;tput sgr0;
-		exit 1;
-	   fi;
-	   # Install app
-	   save_apps_to_db_sqlite_func;
-	   install_apps_func;
-	   echo -e "\E[32mApp $IMAGE installed.";tput sgr0;
-	   echo;
-	   exit 0
-	  ;;
-	
-	u ) IMAGE=$OPTARG;
-	   image_latest_func;
-	   # Installed app?
-	   if [[ -z `list_apps_in_db_func | awk 'BEGIN {OFS = ":"} {print $3, $4}' | grep "$IMAGE"` ]];then
-		echo -e "\E[31mERROR: App not found in db.">&2;tput sgr0;
-		exit 1;
-	   else
-		IMAGE=`docker images --no-trunc | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$IMAGE" | awk -F ':' '{print $NF}'`;
-	   fi;
-	   # Exist app?
-	   if [[ -z `docker images --no-trunc | grep -v 'REPOSITORY' | awk -F ' ' ' {print $3} ' | grep "$IMAGE"` ]];then
-		echo -e "\E[31mERROR: Image not found in registry docker.">&2;tput sgr0;
-		exit 1;
-	   fi;
-	   # Uninstall app
-	   uninstall_apps_func;
-	   delete_apps_to_db_func;
-	   echo -e "\E[32mApp $IMAGE uninstalled.";tput sgr0;
-	   exit 0
-	  ;;
-	
-	c ) IMAGE=$OPTARG;
-	    image_latest_func;
-	    # Exist image?
-	    if [[ -z `docker images --no-trunc | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2} ' | sed "s/ /:/g" | grep "$IMAGE"` ]];then
-		echo -e "\E[31mERROR: Image not found in registry docker. Stop installation.">&2;tput sgr0;
-		exit 1;
-	    fi;
-	    copy_meta_func;
-	    pwd=$PWD;
-	    IMAGE=`echo $IMAGE | sed "s/\//./g"`;
-	    echo;
-	    # Remove exist dirrectory
-	    if [[ -d /tmp/meta_$IMAGE ]];then
-		echo "Removing old dirrectory."
-		rm -r /tmp/meta_$IMAGE;
-	    fi;
-	    mv $TEMPLATE_DIR/meta /tmp/meta_$IMAGE;
-	    cd $pwd;
-	    rm -r $TEMPLATE_DIR;
-	    echo "Meta files are moved to a folder /tmp/meta_$IMAGE";
-	    echo;
-	    exit 0
-	  ;;
-	
-	I ) IMAGE=$OPTARG;
-	    image_latest_func;
-	    copy_meta_func;
-	    pwd=$PWD;
-	    cd $TEMPLATE_DIR/meta;
-	    echo;
-	    cat DESCRIPTION;
-	    echo;
-	    echo "    Time of creation:";
-	    cat BUILDSTAMP;
-	    cd $pwd;
-	    rm -rf $TEMPLATE_DIR;
-	    echo;
-	    exit 0
-	  ;;
-
-	h ) echo "$USAGE"; 
-	    exit 0
-	  ;;
-	
-	-)  case "${OPTARG}" in
-		help)		echo "$USAGE";
-				exit 0
-		;;
-		repos-list)	echo;
-				echo "      List repositories:";
-				echo;
-				sqlite3 $SAM_DB_SQLITE "SELECT Id,ReposFlag,ReposName,ReposURL,ReposUser FROM $SAM_DB_TABLE_REPOS" | column -t -s '|' ; 
-				echo;
-				exit 0
-		;;
-		repos-add)	echo;
-				echo "      Adding repository:";
-				echo;
-				read -e -p "Repository Url: " SAM_DB_TABLE_REPOS_URL;
-				if [[ -z $SAM_DB_TABLE_REPOS_URL ]];then
-					echo -e "\E[31mERROR: Variable from Url is empty.">&2;tput sgr0;
-					exit 1;
-				fi;
-				read -e -p "Name repository: " SAM_DB_TABLE_REPOS_NAME;
-				if [[ -z $SAM_DB_TABLE_REPOS_NAME ]];then
-					echo -e "\E[31mERROR: Variable from name repository is empty.">&2;tput sgr0;
-					exit 1;
-				fi;	
-				
-				read -e -p "Username: " SAM_DB_TABLE_REPOS_USER; 
-				read -s -p "Password: " SAM_DB_TABLE_REPOS_PASS; echo;
-				SAM_DB_TABLE_REPOS_PASS=`echo "$SAM_DB_TABLE_REPOS_PASS" | base64`;
-				read -e -p "Email: "    SAM_DB_TABLE_REPOS_EMAIL;
-				
-				#save in db
-				echo;
-				echo "Saving in db.";
-				sqlite3 $SAM_DB_SQLITE "insert into $SAM_DB_TABLE_REPOS (ReposFlag,ReposName,ReposUrl,ReposUser,ReposPass,ReposEmail) values (' ','$SAM_DB_TABLE_REPOS_NAME','$SAM_DB_TABLE_REPOS_URL','$SAM_DB_TABLE_REPOS_USER','$SAM_DB_TABLE_REPOS_PASS','$SAM_DB_TABLE_REPOS_EMAIL');";
-				unset SAM_DB_TABLE_REPOS_URL;
-				unset SAM_DB_TABLE_REPOS_NAME;
-				unset SAM_DB_TABLE_REPOS_USER;
-				unset SAM_DB_TABLE_REPOS_PASS;
-				unset SAM_DB_TABLE_REPOS_EMAIL;
-				exit 0
-		;;
-		repos-delete)	echo;
-				echo "      Deleting repository:";
-				echo;
-				read -e -p "Enter name of repository: " SAM_DB_TABLE_REPOS_NAME;
-				exist_repos_name_in_db_func;
-
-				#Default repository?
-				if [[ -n `sqlite3 $SAM_DB_SQLITE "select ReposFlag from $SAM_DB_TABLE_REPOS where ReposName='$SAM_DB_TABLE_REPOS_NAME'"` ]]; then
-					echo -e "\E[31mERROR: Repository '$SAM_DB_TABLE_REPOS_NAME' is default.">&2;tput sgr0;
-            				exit 1;
-				fi;
-
-				#delete in db
-				echo;
-				echo "Deleting in db.";
-				sqlite3 $SAM_DB_SQLITE "delete from $SAM_DB_TABLE_REPOS where ReposName='$SAM_DB_TABLE_REPOS_NAME'";
-				unset SAM_DB_TABLE_REPOS_NAME;
-				exit 0
-		;;
-		repos-default)	echo;
-				echo "      Selecting default repository:";
-				echo;
-				read -e -p "Enter name of repository: " SAM_DB_TABLE_REPOS_NAME;
-				exist_repos_name_in_db_func;
-				
-				#reset column
-				echo;
-				echo "Saving in db.";
-				sqlite3 $SAM_DB_SQLITE "update $SAM_DB_TABLE_REPOS SET ReposFlag=' '";
-				#add flag
-				sqlite3 $SAM_DB_SQLITE "update $SAM_DB_TABLE_REPOS SET ReposFlag='*' where ReposName='$SAM_DB_TABLE_REPOS_NAME'";
-				unset SAM_DB_TABLE_REPOS_NAME;
-				exit 0
-		;;
-		*)		if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
-				    echo -e "\E[31mERROR: Non-option argument: '-${OPTARG}'">&2;tput sgr0;
-				    exit 1;
-				fi
-		;;
-	    esac
-	    ;;
-	
-	*) echo
-	  ;;
+                debug)
+                    set -vx;
+                    SAM_ARGUMENTS=`echo $@ | sed 's/--debug //'`
+                    ;;
+                \?)
+                    echo -e "\E[31mERROR: Unknown option: '--$OPTARG'">&2;tput sgr0;
+                    exit 1
+                    ;;
+           esac
+           ;;
+        \?)
+           echo -e "\E[31mERROR: Unknown option: '-$OPTARG'">&2;tput sgr0;
+           exit 1
+           ;;
     esac
 done
 
-if [[ -z $IMAGE ]];then 
-	IMAGE=$1;
-	image_latest_func;
-	if [[ -n `list_apps_in_db_func | awk 'BEGIN {OFS = ":"} {print $3, $4}' | grep "$IMAGE"` ]];then
-	    echo -e "\E[31mERROR: App found in db. Stop installation.">&2;tput sgr0;
-	    exit 1;
-	fi;
-	# Pull
-	docker pull $IMAGE;
-	if [[ $? -eq 0 ]]; then
-		save_apps_to_db_sqlite_func;
-		install_apps_func;
-		echo -e "\E[32mApp $IMAGE installed.";tput sgr0;
-		echo;
-	else
-		echo -e "\E[31mNot found image \"$1\" in docker registry." >&2;tput sgr0;
-		exit 1;
-	fi;
+if [[ -z $SAM_ARGUMENTS ]]; then
+        SAM_ARGUMENTS=`echo $@`;
 fi;
+
+case `echo $SAM_ARGUMENTS | awk ' {print $1} '` in
+        help)	case `echo $SAM_ARGUMENTS | sed 's/help //'` in
+			install)	echo "$USAGE_INSTALL"
+			;;
+			installfile)	echo "$USAGE_INSTALLFILE"
+			;;
+			remove)		echo "$USAGE_REMOVE"
+			;;
+			list) 		echo "$USAGE_LIST"
+			;;
+			info)		echo "$USAGE_INFO"
+			;;
+			addrepo)	echo "$USAGE_ADDREPO"
+			;;
+			removerepo)	echo "$USAGE_REMOVEREPO"
+			;;
+			modifyrepo)	echo "$USAGE_MODIFYREPO"
+			;;
+			listrepos)	echo "$USAGE_LISTREPOS"
+			;;
+			*)
+				echo "$USAGE";
+				echo;
+				if [[ -n `echo $SAM_ARGUMENTS | sed 's/help//'` ]];then
+					echo -e "\E[31mERROR: Unknown command: 'sam $SAM_ARGUMENTS'">&2;tput sgr0;
+                                	exit 1;
+				fi;
+		        	exit 0
+           		;;
+		esac		
+        ;;
+
+        install)	install_func;
+        ;;
+
+        installfile)	installfile_func;
+        ;;
+
+        remove)		remove_func;
+        ;;
+
+        list)		list_func;
+        ;;
+
+        info)		info_func;
+        ;;
+
+        addrepo)        SAM_ARGUMENTS=`echo "$SAM_ARGUMENTS" | sed 's/addrepo //'`;
+			addrepo_func;
+			exit 0
+        ;;
+
+        removerepo)	SAM_ARGUMENTS=`echo "$SAM_ARGUMENTS" | sed 's/removerepo //'`;
+			removerepo_func;
+			exit 0
+        ;;
+
+        modifyrepo)     SAM_ARGUMENTS=`echo "$SAM_ARGUMENTS" | sed 's/modifyrepo //'`;
+			modifyrepo_func;
+			exit 0
+        ;;
+
+        listrepos)	listrepos_func;
+			exit 0
+        ;;
+        *)
+	   echo;
+	   echo "$USAGE";
+           echo -e "\E[31mERROR: Unknown command: 'sam $SAM_ARGUMENTS'">&2;tput sgr0;
+           exit 1
+        ;;
+
+esac;
+
