Added "sam export" command.

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #set -vx
-SAM_VERSION='1.11';
+SAM_VERSION='1.12';
 
 #Configuring
 BIN_DIR=${BIN_DIR:-/opt/bin}
@@ -219,6 +219,9 @@ USAGE="
         search, se              Search image version on private registry.
         info                    Print application info.
         upgrade, up             Upgrade Smilart Os.
+     
+        export, ex              Export images list or archive.
+        import, im              Import images list or archive.
 
      Repository Management:
         addrepo, ar             Add a new repository.
@@ -318,6 +321,23 @@ Modify properties of repositories specified.
     --username                  Set the user name for authentication to the server.
     --password                  Set the password for authentication to the server.
     --email                     Set the email for authentication to the server. 
+
+";
+
+USAGE_EXPORT="
+export (ex) <file> [--all]
+
+Default, export apps list in a special format to a file.
+
+  Command options:
+    --all                       Save apps to gzip archive and add thim to tar. Export to archive.
+
+";
+
+USAGE_IMPORT="
+import (im) <file>
+
+Default, import apps list or archive with apps.
 
 ";
 
@@ -566,6 +586,65 @@ info_func(){
     echo;
 }
 
+export_func(){
+    local FILE_PATH="$1"
+    local EXPORT_LIST_APPS=`sqlite3 $SAM_DB_SQLITE "SELECT ImageName,ImageVersion FROM $SAM_DB_TABLE_INSTALL_APPS"`;
+    local EXPORT_APP
+    local EXPORT_FILE_NAME
+    local PREFIX_IMAGE='smilart'
+    local OS_NAME=`cat /etc/os-release | grep "PRETTY_NAME=" | awk -F '"' '{print $2}'`
+    
+    echo > "$1"
+    if [[ $? -ne 0 ]];then
+         echo -e "\E[31mERROR: Can't create file $1.">&2;tput sgr0;
+    fi;    
+
+    if [[ "$GETOPT_ALL" != "true" ]];then
+    	echo "#$OS_NAME#" > $1;
+        echo "$EXPORT_LIST_APPS" >> $1;
+        
+    else
+        local TMPL_DIR=`mktemp -d`;
+        echo "Creating tmp directory $TMPL_DIR";
+
+        echo "Saving apps to gzip archives:"
+        for EXPORT_APP in `echo "$EXPORT_LIST_APPS"`
+        do
+            EXPORT_FILE_NAME="`echo $EXPORT_APP | awk -F '|' '{print $1 "-" $2 ".gz"}'`"
+            echo "   -> $TMPL_DIR/$EXPORT_FILE_NAME"
+            docker save $PREFIX_IMAGE/`echo $EXPORT_APP | awk -F '|' '{print $1 ":" $2}'` | gzip > $TMPL_DIR/$EXPORT_FILE_NAME;
+            if [[ $? -ne 0 ]];then
+                echo -e "\E[31mERROR: Can't save image.">&2;tput sgr0;
+            fi;
+        done;
+
+        echo "Creating images list"
+        echo "#$OS_NAME#" > $TMPL_DIR/imagelist;
+        if [[ $? -ne 0 ]];then
+            echo -e "\E[31mERROR: Can't create export file $TMPL_DIR/imagelist.">&2;tput sgr0;
+            exit 1;
+        fi;
+        echo "$EXPORT_LIST_APPS" >> $TMPL_DIR/imagelist;
+
+        echo "Creating $1"
+        (cd $TMPL_DIR && tar cf archive.tar *)
+        if [[ $? -ne 0 ]];then
+            echo -e "\E[31mERROR: Can't create archive $TMPL_DIR/archive.tar.">&2;tput sgr0;
+        fi;
+        mv $TMPL_DIR/archive.tar "$1"
+        if [[ $? -ne 0 ]];then
+            echo -e "\E[31mERROR: Can't create archive '$1'.">&2;tput sgr0;
+        fi;   
+
+        echo "Clearing tmp directories"
+        rm -rf $TMPL_DIR
+        if [[ $? -ne 0 ]];then
+            echo -e "\E[31mERROR: Can't remove $TMPL_DIR.">&2;tput sgr0;
+        fi;
+    fi
+    echo -e "\E[32mComplete. Saved to '$1'.";tput sgr0
+}
+
 addrepo_func(){
     #It is correct name and url?
     if [[ -z $GETOPT_NAME ]] || [[ -z $GETOPT_SERVER ]];then
@@ -775,6 +854,14 @@ help_func(){
             echo "$USAGE_MODIFYREPO";
             exit 0
             ;;
+        export|ex)
+            echo "$USAGE_EXPORT";
+            exit 0
+            ;;
+        import|im)
+            echo "$USAGE_IMPORT";
+            exit 0
+            ;;
         listrepos|lr)
             echo "$USAGE_LISTREPOS";
             exit 0
@@ -791,7 +878,7 @@ help_func(){
 }
 
 ###Case section
-SAM_ARGUMENT=`getopt -o h:x --long help:,debug,raw,default,name:,server:,username:,password:,email: --name "sam" -- "$@"`
+SAM_ARGUMENT=`getopt -o h:x --long help:,debug,raw,default,name:,server:,username:,password:,email:,all --name "sam" -- "$@"`
 eval set -- "$SAM_ARGUMENT";
 unset SAM_ARGUMENT;
 unset GETOPT_RAW;
@@ -801,6 +888,7 @@ unset GETOPT_SERVER;
 unset GETOPT_USERNAME;
 unset GETOPT_PASSWORD;
 unset GETOPT_EMAIL;
+unset GETOPT_ALL;
 
 while true ; do
     case "$1" in
@@ -841,6 +929,10 @@ while true ; do
             GETOPT_EMAIL=$2;
             shift 2
             ;;
+        --all)
+            GETOPT_ALL='true';
+            shift 
+            ;;
         --)
             shift;
             case "$1" in
@@ -872,6 +964,16 @@ while true ; do
                 modifyrepo|mr)
                     shift;
                     modifyrepo_func $1;
+                    exit 0
+                    ;;
+                export|ex)
+                    shift;
+                    export_func $1;
+                    exit 0
+                    ;;
+                import|im)
+                    shift;
+                    import_func $1;
                     exit 0
                     ;;
                 list)
