Refactoring. Fixed 'Does not' to 'Doesn't' in messages.

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -406,7 +406,7 @@ USAGE_SEARCH="
 search (se) [<image_name>]
 
 Search application in remote repository.
-WARN: Search does not work in official Docker Hub repository.
+WARN: Search doesn't work in official Docker Hub repository.
 
 ";
 
@@ -848,7 +848,7 @@ import_func(){
     #Check OS
     local OS_NAME="`cat /etc/os-release | grep "PRETTY_NAME=" | awk -F '"' '{print $2}'`";
     if [[ -z "$OS_NAME" ]];then
-        echo -e "\E[31mERROR: File /etc/os-release does not contain variable PRETTY_NAME.">&2;tput sgr0;
+        echo -e "\E[31mERROR: File /etc/os-release doesn't contain variable PRETTY_NAME.">&2;tput sgr0;
         exit 1;
     fi;
     local OS_EXPORT="`cat $TMPL_DIR/imagelist | head -1 | awk -F '#' '{print $2}'`";
